UrbanSolution.Web/Areas/Manager/Controllers/UrbanIssueController.cs
namespace UrbanSolution.Web.Areas.Manager.Controllers
{
    using Infrastructure.Extensions;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Services;
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using UrbanSolution.Models;
    using UrbanSolution.Services.Manager;
    using UrbanSolution.Web.Models.Areas.Manager;
    using static UrbanSolutionUtilities.WebConstants;

    public class UrbanIssueController : BaseController
    {
        private readonly IManagerIssueService managerIssues;
        private readonly IIssueService issues;

        public UrbanIssueController(
            UserManager<User> userManager,
            IManagerIssueService managerIssues,
            IIssueService issues)
            : base(userManager)
        {
            this.managerIssues = managerIssues;
            this.issues = issues;
        }

        public async Task<IActionResult> Index()
        {
            var manager = await this.UserManager.GetUserAsync(this.User);

            var model = new NewIssuesIndexModel
            {
                RegionType = manager.ManagedRegion
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> New(int page = 1)
        {
            var manager = await this.UserManager.GetUserAsync(this.User);

            RegionType? region = manager.ManagedRegion;

            (int totalItems, var issues) = await this.managerIssues
                .AllAsync<IssueTableRowViewModel>(isApproved: false, region, page, takeCount: IssuesOnTablePage);

            var model = new NewIssuesTablePartialViewModel
            {
                Isssues = issues,
                Page = page,
                PagesCount = (int)Math.Ceiling((double)totalItems / IssuesOnTablePage)
            };

            return this.PartialView("_NewIssuesTablePartial", model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var issue = await this.issues.GetAsync<IssueEditViewModel>(id);

            this.SetModelSelectListItems(issue);

            return this.ViewOrNotFound(issue);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, IssueEditViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                this.SetModelSelectListItems(model);
                return this.View(model);
            }

            var manager = await this.UserManager.GetUserAsync(User);

            var isUpdated = await this.managerIssues.UpdateAsync(
                manager, model.Id, model.Title, model.Description,
                model.Region, model.Type, model.AddressStreet, model.PictureFile);

            if (!isUpdated)
            {
                return this.RedirectToAction("Details", "Issue", new { id, Area = "" })
                    .WithDanger(string.Empty, CantEditIssueForAnotherRegion);
            }

            return this.RedirectToAction("Details", "Issue", new { id, Area = "" })
                .WithSuccess(string.Empty, IssueUpdateSuccess);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var manager = await this.UserManager.GetUserAsync(this.User);

            var isDeleted = await this.managerIssues.DeleteAsync(manager.Id, manager.ManagedRegion, id);
            if (!isDeleted)
            {
                return this.RedirectToAction("Index", "UrbanIssue", new { Area = "Manager" })
                    .WithDanger(string.Empty, CantDeleteIssueForAnotherRegion);
            }

            return this.RedirectToAction("Index", "UrbanIssue", new { Area = "Manager" })
                .WithSuccess(string.Empty, IssueDeleteSuccess);
        }

        public async Task<IActionResult> Approve(int id)
        {
            var manager = await this.UserManager.GetUserAsync(User);

            var isApproved = await this.managerIssues.ApproveAsync(manager, id);
            if (!isApproved)
            {
                return this.RedirectToAction(nameof(Index)).WithDanger(string.Empty, CantApproveIssueForAnotherRegion);
            }

            return this.RedirectToAction(nameof(Index)).WithSuccess(string.Empty, IssueApprovedSuccess);
        }

        private void SetModelSelectListItems(IssueEditViewModel model)
        {
            model.Regions = Enum.GetNames(typeof(RegionType))
                .Select(r => new SelectListItem
                { Text = r, Value = r })
                .ToList();

            model.IssueTypes = Enum.GetNames(typeof(IssueType))
                .Select(i => new SelectListItem
                {
                    Text = (Enum.Parse<IssueType>(i)).ToFriendlyName(),
                    Value = i
                });
        }
    }
}

UrbanSolution.Web/Components/UrbanIssuesMapWithMarkersViewComponent.cs
namespace UrbanSolution.Web.Components
{
    using Infrastructure.Extensions;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Configuration;
    using System;
    using System.Threading.Tasks;
    using UrbanSolution.Models;
    using UrbanSolution.Web.Models.Issues;
    using static UrbanSolutionUtilities.WebConstants;
    
    [ViewComponent(Name = ViewComponentUrbanIssuesMapWithMarkersName)]
    public class UrbanIssuesMapWithMarkersViewComponent : ViewComponent
    {
        private readonly IConfiguration configuration;

        public UrbanIssuesMapWithMarkersViewComponent(IConfiguration configuration)
        {
            this.configuration = configuration;
        }

        public async Task<IViewComponentResult> InvokeAsync(RegionType region)
        {
            (double mapRegLat, double mapRegLong, double mapRegZoom) = region.GetMapPositions();

            var apiKey = this.configuration.GetSection("Google:MapsApiKey").Value;

            var model = new MapIssueMarkerComponentViewModel
            {
                ApiKey = apiKey,
                Latitude = mapRegLat.ToString().Replace(",", "."),
                Longitude = mapRegLong.ToString().Replace(",", "."),
                Zoom = mapRegZoom.ToString().Replace(",", ".")
            };

            return this.View(model);
        }
    }
}

UrbanSolution.Web/Areas/Manager/Views/UrbanIssue/Edit.cshtml
@model IssueEditViewModel
@{
    ViewData["Title"] = "Edit issue";
}

<div row class="text-info">
    <h3 class="text-center">@this.ViewData["Title"]</h3>
    <hr />
</div>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <form asp-area="Manager" asp-action="Edit" asp-route-id="@Model.Id"
              method="post" enctype="multipart/form-data">
            <div class="form-group row">
                <div class="col-xs-6">
                    <label asp-for="Title"></label>
                    <div>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-xs-6">
                    <label asp-for="AddressStreet"></label>
                    <div>
                        <input asp-for="AddressStreet" class="form-control" />
                        <span asp-validation-for="AddressStreet" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div clas="row">
                <div class="form-group row">
                    <label asp-for="PictureFile"></label>
                    <div>
                        <input asp-for="PictureFile" class="form-control" />
                        <span asp-validation-for="PictureFile" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="7" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="form-group col-xs-6">
                    <label asp-for="Region"></label>
                    <div>
                        <select asp-for="Region" asp-items="@Model.Regions" selected="@Model.Region" class="form-control"></select>
                        <span asp-validation-for="Region" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group col-xs-6">
                    <label asp-for="Type"></label>
                    <div>
                        <select asp-for="Type" asp-items="@Model.IssueTypes" selected="@Model.Type" class="form-control"></select>
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row" style="text-align: center">
                <button type="submit" class="btn btn-default">Edit Issue</button>
            </div>
        </form>
    </div>
</div>

UrbanSolution.Web/Areas/Manager/Views/UrbanIssue/Index.cshtml
@model NewIssuesIndexModel
@{
    ViewData["Title"] = "New issues";
}

<div row class="text-info text-center">
    <h3>@this.ViewData["Title"]</h3>
</div>

@*Navigation Tabs*@
<div class="row">
    <ul class="nav nav-tabs nav-justified">
        <li id="onMap" class="active" role="presentation"><a href="#">On Map</a></li>
        <li id="inTable" role="presentation"><a href="#">In Table</a></li>
    </ul>
</div>

<hr />

@*component view with map with markers for issues location*@
<div id="mapDiv">
    @await Component.InvokeAsync("UrbanIssuesMapWithMarkers", Model.RegionType)
</div>


<div id="newIssuesTable">
    <div id="issuesDiv">
    </div>
    <ul id="issuesPagination" class="pagination">
    </ul>
</div>


@*issues for carousel*@
@*<div class="slick-issues row issues-listing" id="wrapper">
        @await Html.PartialAsync("_IssuesListingPartial", Model)
    </div>*@

@*Modal*@
<div class="modal fade" id="issueDetailsModal" tabindex="-1" role="dialog" aria-labelledby="largeModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Details</h4>
            </div>
            <div class="modal-body">
                <div id="detailsModelBody">
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <input id="modalIssueId" type="hidden" />
            <button id="modalBtnMore" type="button" class="btn btn-primary">
                Show more
            </button>
            @*<button id="modalBtnApprove" type="button" class="btn btn-primary">
                Approve
            </button>
            <button type="button" class="btn btn-warning" onclik="editIssue()">
                Edit
            </button>
            <button type="button" class="btn btn-danger" onclik="deleteIssue()">
                Delete
            </button>*@
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
</div>

@*<div row class="text-info text-center">
      <br />
      <h4>@NoIssuesToShow</h4>
      <br />
    </div>*@


@section Scripts
{
    @*<partial name="_SlickCarouselIssuesListingScriptPartial" />*@

    <script>
        //On click on Table TAB
        $('#inTable').click(function () {
            $('#mapDiv').hide();
            $('#newIssuesTable').show();

            $('#onMap').removeClass('active');
            $('#inTable').addClass('active');
        })
        //ON Click on Map TAB
        $('#onMap').click(function () {
            $('#mapDiv').show();
            $('#newIssuesTable').hide();

            $('#onMap').addClass('active');
            $('#inTable').removeClass('active');
        })
    </script>

    <script>
        $('#inTable').click(function () {
            //if issues has been loaded to not load them again
            if ($('#issuesDiv').children().length == 0) {
                loadIssues(1);
            }
        });

        // Load Issues - page parameter is passed when pagination link is clicked
        function loadIssues(page) {
            $.ajax({
                url: "/Manager/UrbanIssue/New?page=" + page,
                type: "GET",
                dataType: "html",
                success: function (issuesHtml) {
                    fadeInEffect(issuesHtml);
                    var pagesCount = $("#pagesCount").val();
                    var page = $("#page").val();

                    createPagination(page, pagesCount);
                }
            });
        }

        // CREATE Pagination
        function createPagination(page, pagesCount) {
            $("#issuesPagination").empty();

            //Show or Hide Button for Previous Page
            if (+page !== 1) {
                var element = `<li><a onclick="paginationLiClicked(${+page - 1})" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>`;
                $("#issuesPagination").append(element);
            }

            //previos pages buttons
            var i;
            var label;
            for (i = 5; i >= 1; i--) {
                if (+page - i > 0) {
                    label = +page - +i;
                    var element = `<li class="inactive"><a onclick="paginationLiClicked(${label})">${label}<span class="sr-only"></span></a></li>`;
                    $("#issuesPagination").append(element);
                }
            }

            //current page button
            $("#issuesPagination").append(`<li class="active"><a>${page}</a></li>`);

            //next pages buttons
            for (i = 1; i < 5; i++) {
                if (+page + i <= +pagesCount) {
                    label = +page + +i;
                    var element = `<li class="inactive"><a onclick="paginationLiClicked(${label})">${label}<span class="sr-only"></span></a></li>`;
                    $("#issuesPagination").append(element);
                }
            }

            //Show or not button for next page
            if (+page + 1 <= +pagesCount) {
                var element = `<li><a onclick="paginationLiClicked(${+page + 1})" aria-label="Next"><span aria-hidden="true"> &raquo;</span></a></li>`;
                $("#issuesPagination").append(element);
            }
        }

        function paginationLiClicked(page) {
            $("#issuesPagination").empty();
            loadIssues(page);
        }

        function fadeInEffect(html) {
            $("#issuesDiv").empty();
            $("#issuesDiv").html(html).hide().fadeIn(1000);
        }

    </script>
}