UrbanSolution.Web/Areas/Manager/Controllers/IssuesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UrbanSolution.Models;
using UrbanSolution.Services.Manager;
using UrbanSolution.Services.Manager.Models;
using UrbanSolution.Web.Infrastructure;
using UrbanSolution.Web.Infrastructure.Extensions;

namespace UrbanSolution.Web.Areas.Manager.Controllers
{    
    public class IssuesController : BaseController
    {
        private readonly IIssueService issues;

        public IssuesController(
            UserManager<User> userManager, 
            RoleManager<IdentityRole> roleManager,
            IIssueService issues) 
            : base(userManager, roleManager)
        {
            this.issues = issues;
        }

        public async Task<IActionResult> Index()
        {
            var notApproved = await this.issues.AllAsync(isApproved: false);

            return View(notApproved);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var issue = await this.issues.GetAsync(id);

            if (issue == null)
            {
                return this.BadRequest();
            }

            this.SetModelSelectListItems(issue);
            return this.View(issue);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, UrbanIssueEditServiceViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                this.SetModelSelectListItems(model);
                return this.RedirectToAction(nameof(Edit), "Issues", new {id});
            }

            await this.issues.Update(model.Id, model.Name, model.IssuePictureUrl, model.Description, model.Region, model.Type,
                model.AddressStreet, model.StreetNumber);

            this.TempData.AddSuccessMessage(WebConstants.IssueUpdateSuccess);

            return this.RedirectToAction("Details", "Issue", new {id, Area = ""});
        }

        public async Task<IActionResult> Delete(int id)
        { 
            bool exists = await this.issues.ExistsAsync(id);             //TODO: make a filter
            if (!exists)
            {
                this.TempData.AddErrorMessage(WebConstants.IssueNotFound);
                return this.NotFound();
            }

            await this.issues.Delete(id);

            this.TempData.AddSuccessMessage(WebConstants.IssueDeleteSuccess);

            return this.RedirectToAction("Index", "Issues", new {Area = "Manager"});
        }

        public async Task<IActionResult> Approve(int id)
        {
            bool exists = await this.issues.ExistsAsync(id);
            if (!exists)
            {
                this.TempData.AddErrorMessage(WebConstants.IssueNotFound);
                return this.NotFound();
            }

            await this.issues.ApproveAsync(id);
            this.TempData.AddSuccessMessage(WebConstants.IssueApprovedSuccess);

            return this.RedirectToAction(nameof(Index));
        }

        private void SetModelSelectListItems(UrbanIssueEditServiceViewModel model)  //TODO: make it Generic
        {
            model.Regions = Enum.
                GetNames(typeof(RegionType))
                .Select(r => new SelectListItem
                {
                    Text = r,
                    Value = r
                }).ToList();

            model.IssueTypes = Enum
                .GetNames(typeof(IssueType))
                .Select(i => new SelectListItem
                {
                    Text = (Enum.Parse<IssueType>(i)).ToFriendlyName(),
                    Value = i
                });
        }
    }
}

UrbanSolution.Web/Components/IssueDetailsButtonsViewComponent.cs
namespace UrbanSolution.Web.Components
{
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;
    using UrbanSolution.Models;
    using static UrbanSolutionUtilities.WebConstants;

    [ViewComponent(Name = ViewComponentIssueDetailsButtonsName)]
    public class IssueDetailsButtonsViewComponent : ViewComponent
    {
        private readonly UserManager<User> userManager;

        public IssueDetailsButtonsViewComponent(UserManager<User> userManager)
        {
            this.userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync(RegionType region)
        {
            var user = await this.userManager.GetUserAsync(this.UserClaimsPrincipal);

            if (user != null)
            {
                this.ViewData[ViewDataManagerRegionKey] = user.ManagedRegion.ToString();
                this.ViewData[IssueRegionKey] = region;
            }

            return this.View();
        }
    }
}

UrbanSolution.Web/Components/IssueDetailsMapViewComponent.cs
namespace UrbanSolution.Web.Components
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Configuration;
    using static UrbanSolutionUtilities.WebConstants;
    using UrbanSolution.Web.Models.Issues;

    [ViewComponent(Name = ViewComponentIssueDetailsMapName)]
    public class IssueDetailsMapViewComponent : ViewComponent
    {
        private readonly IConfiguration configuration;

        public IssueDetailsMapViewComponent(IConfiguration configuration)
        {
            this.configuration = configuration;
        }

        public IViewComponentResult Invoke(IssueDetailsModel model)
        {
            var viewModel = new MapIssueMarkerComponentViewModel
            {
                ApiKey = this.configuration.GetSection("Google:MapsApiKey").Value,
                Latitude = model.Latitude,
                Longitude = model.Longitude,
                Zoom = ZoomMapIssueDetails.ToString().Replace(",", ".")
            };

            return this.View(viewModel);
        }
    }
}

UrbanSolution.Web/Controllers/IssueController.cs
namespace UrbanSolution.Web.Controllers
{
    using Infrastructure.Extensions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Services;
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using UrbanSolution.Models;
    using UrbanSolution.Web.Models.Issues;
    using static UrbanSolutionUtilities.WebConstants;

    [Authorize]
    public class IssueController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IIssueService issues;

        public IssueController(IIssueService issues, UserManager<User> userManager)
        {
            this.issues = issues;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = new IssuesIndexModel();

            return this.View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Get([FromQuery] IssuesSortAndFilterModel model)
        {
            (int pagesCount, var modelIssues) = await this.issues
                .AllAsync<IssuesListingModel>(
                isApproved: true, model.RowsCount, model.ToPage, model.RegionFilter, model.TypeFilter, model.SortType);

            var partialModel = new IssuesListingViewModel
            {
                Issues = modelIssues,
                PagesCount = pagesCount,
                Page = model.ToPage
            };

            return this.PartialView("_IssuesListingPartial", partialModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {            
            if(this.User.IsInRole(ManagerRole))
            {
                var user = await this.userManager.GetUserAsync(this.User);
                this.ViewData[ViewDataManagerRegionKey] = user.ManagedRegion?.ToString();
            }

            var issueModel = await this.issues.GetAsync<IssueDetailsModel>(id);
            if (issueModel == null)
            {
                return this.RedirectToAction("Index").WithDanger(string.Empty, NoIssueInDb);
            }

            return this.View(issueModel);
        }

        [HttpGet]
        public async Task<ActionResult> GetDetails(int id)
        {
            var issueDetails = await this.issues.GetAsync<IssueDetailsViewModel>(id);

            return this.PartialView("_IssueDetailsPartial", issueDetails);
        }

        [HttpGet]
        public IActionResult Publish()
        {
            var model = new PublishIssueViewModel();

            this.SetModelSelectListItems(model);

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Publish(PublishIssueViewModel model)
        {
            if (!ModelState.IsValid)
            {
                this.SetModelSelectListItems(model);
                return this.View(model);
            }

            var userId = this.userManager.GetUserId(User);

            var issueId = await this.issues.UploadAsync(userId, model.Title, model.Description, model.PictureFile, model.IssueType, model.Region, model.Address, model.Latitude, model.Longitude);

            return this.RedirectToAction("Details", "Issue", new { area = "", id = issueId })  //TODO: remove area
                .WithSuccess(string.Empty, IssueUploaded);
        }

        [HttpGet]
        public async Task<IActionResult> InfoBoxDetails()
        {
            var user = await this.userManager.GetUserAsync(this.User);
            RegionType? region = user.ManagedRegion;

            var data = await this.issues
                .AllMapInfoDetailsAsync<IssueMapInfoBoxModel>(areApproved: false, region: region);

            return this.Ok(data);
        }
       
        [HttpPost]
        public async Task<ActionResult<int>> UploadImage(IFormFile file)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var picId = await this.issues.UploadIssueImageAsync(user.Id, file);

            return this.Ok(picId);
        }

        private void SetModelSelectListItems(PublishIssueViewModel model)
        {
            model.Regions = Enum.GetNames(typeof(RegionType)).Where(regionName => !regionName.EndsWith("All"))
                .Select(r => new SelectListItem
                {
                    Text = r,
                    Value = r
                }).ToList();

            model.IssueTypes = Enum.GetNames(typeof(IssueType))
                .Select(i => new SelectListItem
                {
                    Text = (Enum.Parse<IssueType>(i)).ToFriendlyName(),
                    Value = i
                });
        }
    }
}

UrbanSolution.Web/Views/Issue/Details.cshtml
@model IssueDetailsModel
@{
    ViewData["Title"] = $@"Details for issue ""{Model.Title}""";
}

<div row class="text-info">
    <h3 class="text-center">@this.ViewData["Title"]</h3>
    <br />
</div>

<div class="row">

    <div class="form-group col-md-5">
        <div class="row">
            <h4>
                <em class="text-info">
                    <i class="glyphicon glyphicon-cloud-upload"></i> @Model.Publisher
                </em>
                <em class="text-info">
                    <i class="glyphicon glyphicon-hourglass"></i> @Model.PublishedOn.ToShortDateString()
                </em>
            </h4>
            <h4>
                <em class="text-info">
                    <i class="glyphicon glyphicon-home"></i> @Model.AddressStreet
                </em>
            </h4>
            <div>
                <h4>
                    Type: <em class="text-info">@Model.Type.ToFriendlyName()</em>,
                    Region: <em class="text-info">@Model.Region</em>
                </h4>
            </div>

            @* Buttons for approve/delete/edit... *@
            @await Component.InvokeAsync("IssueDetailsButtons", Model.Region)

            <h3><em>@Model.Description</em></h3>
        </div>
    </div>

    <div class="form-group col-md-5">
        @* Showing the map for the issue with marker for location *@
        @await Component.InvokeAsync("IssueDetailsMap", Model)
    </div>

</div>

UrbanSolution.Web/Views/Issue/Index.cshtml
@model IssuesIndexModel
@{
    this.ViewData[TitleKey] = "Approved Issues";
}

<div row class="text-info text-center">
    <h4><strong>@this.ViewData[TitleKey]</strong></h4>
</div>

<div class="form-group row text-center">

    <div class="row btn-group-justified">
        @*Filtering*@
        <div class="col-lg-4">
            <div class="form-inline">
                @*Filtering by Region*@
                <select id="regionSelect" name="RegionFilter" class="form-control">
                    <option selected value="@(OptionAllRegions)">All Regions</option>
                    @foreach (KeyValuePair<string, string> kvp in Model.RegionFilter)
                    {
                        <option value="@kvp.Value">@kvp.Key</option>
                    }
                </select>
                @*Filtering by Issue Type*@
                <select id="typeSelect" name="TypeFilter" class="form-control">
                    <option selected value="@null">@(OptionAllIssuesTypes)</option>
                    @foreach (KeyValuePair<string, string> kvp in Model.TypeFilter)
                    {
                        <option value="@kvp.Value">@kvp.Key</option>
                    }
                </select>
                <button id="filterBtn" type="submit" value="" class="btn btn-default">Filter</button>
            </div>
        </div>
        @* Sort by Publish Time (First newest or oldest approved issues) *@
        <div class="col-lg-2">
            <div class="form-inline">
                <select id="sortType" name="SortType" class="form-control" aria-selected="True">
                    @foreach (KeyValuePair<string, string> kvp in Model.SortingType)
                    {
                        <option value="@kvp.Value">@kvp.Key</option>
                    }
                </select>
                <button id="sortBtn" type="submit" value="" class="btn btn-default"><i class="glyphicon glyphicon-sort-by-alphabet"></i></button>
            </div>
        </div>
        @*change rows*@
        <div class="col-lg-2">
            <div class="form-inline">
                <select id="rowsCount" name="RowsCount" class="form-control" aria-selected="True">
                    @foreach (int rows in (int[])Enum.GetValues(typeof(RowsOnPage))) //TODO: Enumeration from Model?
                    {
                        <option value="@rows">@rows</option>
                    }
                </select>
                <button id="rowsCountBtn" type="submit" value="" class="btn btn-default"><i class="glyphicon glyphicon-align-justify"></i></button>
            </div>
        </div>

        @*jump to page*@
        <div class="col-lg-2">
            <div class="input-group">
                <input type="number" id="toPage" name="ToPage" class="form-control" min="1" value="1" />
                <span class="input-group-btn">
                    <button id="goToPageBtn" type="submit" value="" class="btn btn-default"><i class="glyphicon glyphicon-share-alt"></i></button>
                </span>
            </div>
        </div>
    </div>
    <hr />

    @* Div for issues partial loaded with Ajax request *@
    <div id="issuesListing" class="row issues-listing">
    </div>

    @* Pagination *@
    <ul id="issuesPagination" class="pagination">
    </ul>

</div>

@section Scripts {

    <script>
        $(document).ready(function () {
            loadIssues();
        });

        //page parameter is passed when pagination link is clicked
        function loadIssues(page) {
            var data = {
                RegionFilter: $("#regionSelect").find(":selected").val(),
                TypeFilter: $("#typeSelect").find(":selected").text(),
                SortType: $("#sortType").find(":selected").val(),
                RowsCount: $("#rowsCount").find(":selected").val(),
                ToPage: page ?? $("#toPage").val() 
            };

            $.ajax({
                url: "/Issue/Get?" + $.param(data),
                type: "GET",
                dataType: "html",
                success: function (issuesHtml) {
                    console.log(issuesHtml);

                    fadeInEffect(issuesHtml);
                    var pagesCount = $("#pagesCount").val();
                    var page = $("#page").val();

                    $("#toPage").attr({ "max": pagesCount, "value": page });

                    createPagination(page, pagesCount);
                }
            });
        }

        function createPagination(page, pagesCount) {
            $("#issuesPagination").empty();

            //Show or Hide Button for Previous Page
            if (+page !== 1) {
                var element = `<li><a onclick="paginationLiClicked(${+page - 1})" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>`;
                $("#issuesPagination").append(element);
            }

            //previos pages buttons
            var i;
            var label;
            for (i = 5; i >= 1; i--) {
                if (+page - i > 0) {
                    label = +page - +i;
                    var element = `<li class="inactive"><a onclick="paginationLiClicked(${label})">${label}<span class="sr-only"></span></a></li>`;
                    $("#issuesPagination").append(element);
                }
            }

            //current page button
            $("#issuesPagination").append(`<li class="active"><a>${page}</a></li>`);

            //next pages buttons
            for (i = 1; i < 5; i++) {
                if (+page + i <= +pagesCount) {
                    label = +page + +i;
                    var element = `<li class="inactive"><a onclick="paginationLiClicked(${label})">${label}<span class="sr-only"></span></a></li>`;
                    $("#issuesPagination").append(element);
                }
            }

            //Show or not button for next page
            if (+page + 1 <= +pagesCount) {
                var element = `<li><a onclick="paginationLiClicked(${+page + 1})" aria-label="Next"><span aria-hidden="true"> &raquo;</span></a></li>`;
                $("#issuesPagination").append(element);
            }
        }

        function paginationLiClicked(page) {
            $("#issuesPagination").empty();
            loadIssues(page);
        }

        function fadeInEffect(html) {
            $("#issuesListing").empty();
            $("#issuesListing").html(html).hide().fadeIn(1000);
        }

        $("#filterBtn").click(function () {
            $("#toPage").val(1);
            loadIssues();
        });

        $("#sortBtn").click(function () {
            loadIssues();
        });

        $("#rowsCountBtn").click(function () {
            $("#toPage").val(1);
            loadIssues();
        });

        $("#goToPageBtn").click(function () {
            loadIssues();
        });

    </script>
}

UrbanSolution.Web/Views/Issue/Publish.cshtml
@inject IConfiguration Configuration
@inject IAntiforgery AF

@model PublishIssueViewModel
@{
    ViewData["Title"] = "Publish Issue";
    var apiKey = Configuration.GetSection("Google:MapsApiKey").Value;
}

<h3 class="text-center">@this.ViewData["Title"]</h3>
<hr />

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div asp-validation-summary="All" class="text-danger"></div>

        <form id="fileinfo" enctype="multipart/form-data" method="post" name="fileinfo">
            <label>Picture File</label>
            <input id="picFile" type="file" class="form-control" />
        </form>

        <button id="uploadPicture" type="submit" class="btn btn-default">Upload</button>

        <form method="post" id="urbanForm" enctype="multipart/form-data">
            <div class="row">
                <div class="form-group col-xs-6">
                    <label asp-for="Title"></label>
                    <div>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group col-xs-6">
                    <label asp-for="PictureFile"></label>
                    <div>
                        <input asp-for="PictureFile" class="form-control" />
                        <span asp-validation-for="PictureFile" class="text-danger"></span>
                    </div>
                </div>

            </div>

            <label>Enter location in the map</label>
            <input id="pac-input" class="controls" type="text" placeholder="Enter a location" />
            <div class="form-group">
                <div id="map" style="height: 400px;"></div>
            </div>
            <div id="infowindow-content">
                <span id="place-name" class="title"></span><br>
                Place ID <span id="place-id"></span><br>
                <span id="place-address"></span>
            </div>


            <div class="row">
                <div class="form-group col-sm-12">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button" id="GetAddress">Get Address</button>
                        </span>
                        <input asp-for="Address" class="form-control" placeholder="Adress..." />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="2" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="form-group col-xs-6">
                    <label asp-for="Region"></label>
                    <div>
                        <select asp-for="Region" asp-items="Model.Regions" class="form-control"></select>
                        <span asp-validation-for="Region" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group col-xs-6">
                    <label asp-for="IssueType"></label>
                    <div>
                        <select asp-for="IssueType" asp-items="Model.IssueTypes" class="form-control"></select>
                        <span asp-validation-for="IssueType" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <input type="hidden" id="Latitude" name="Latitude" />
            <input type="hidden" id="Longitude" name="Longitude" />
            <input type="hidden" id="Town" name="Town" value="Plovdiv" />
            <hr />

            <div class="row" style="text-align: center">
                <button type="submit" id="publish" class="btn btn-default">Publish</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {

    <partial name="_ValidationScriptsPartial" />

    <script>
        $("#uploadPicture").click(function () {
            var formData = new FormData();
            formData.append("file", document.getElementById("picFile").files[0]);
            $.ajax({
                url: "/Issue/uploadImage",
                type: "POST",
                data: formData,
                headers: { 'X-CSRF-TOKEN': "@(AF.GetTokens(this.Context).RequestToken)" },
                processData: false,
                contentType: false,
                success: function (data) {
                    console.log(data);
                }
            });
        });
    </script>

    <script>
        var map;
        var place;
        var streetName;
        var coordinates = {};
        var town = "";

        function initMap() {
            var map = new google.maps.Map(
                document.getElementById('map'),
                {
                    center: { lat: @(MapCenterLatitude), lng: @(MapCenterLongitude) },
                    zoom: @(MapCenterZoom),
                });

            var input = document.getElementById('pac-input');

            var autocomplete = new google.maps.places.Autocomplete(input);
            autocomplete.bindTo('bounds', map);

            map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

            var infowindow = new google.maps.InfoWindow();
            var infowindowContent = document.getElementById('infowindow-content');
            infowindow.setContent(infowindowContent);

            var marker = new google.maps.Marker({
                map: map,
                animation: google.maps.Animation.DROP
            });

            marker.addListener('click',
                function() {
                    infowindow.open(map, marker);
                });

            autocomplete.addListener('place_changed',
                function() {
                    infowindow.close();
                    place = autocomplete.getPlace();
                    if (!place.geometry) {
                        return;
                    }

                    if (place.geometry.viewport) {
                        map.fitBounds(place.geometry.viewport);
                    } else {
                        map.setCenter(place.geometry.location);
                        map.setZoom(17);
                    }

                    //
                    coordinates.latitude = place.geometry.location.lat();
                    coordinates.longitude = place.geometry.location.lng();

                    // Set the position of the marker using the place ID and location.
                    marker.setPlace({
                        placeId: place.place_id,
                        location: place.geometry.location
                    });

                    marker.setVisible(true);

                    streetName = place.name.trim();
                    var pointInfo = place.formatted_address.split(",");
                    town = pointInfo[2].trim();

                    infowindowContent.children['place-name'].textContent = place.name;
                    infowindowContent.children['place-id'].textContent = place.place_id;
                    infowindowContent.children['place-address'].textContent =
                        place.formatted_address;

                    infowindow.open(map, marker);
                });
        }

        $("#GetAddress").click(function() {
            $("#Address").val(streetName);

            $("#Latitude").val(coordinates.latitude);
            $("#Longitude").val(coordinates.longitude);
            $("#Town").val(town);
        });
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=@(apiKey)&libraries=places&callback=initMap"
            async defer>
    </script>

}