UrbanSolution.Web/Components/DynamicMenuViewComponent.cs
namespace UrbanSolution.Web.Components
{
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;
    using UrbanSolution.Models;
    using static UrbanSolutionUtilities.WebConstants;

    [ViewComponent(Name = ViewComponentDynamicMenuName)]
    public class DynamicMenuViewComponent : ViewComponent
    {
        private readonly UserManager<User> userManager;

        public DynamicMenuViewComponent(UserManager<User> userManager)
        {
            this.userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = await this.userManager.GetUserAsync(this.UserClaimsPrincipal);

            if (user != null)
            {
                this.ViewData[ViewDataUsernameKey] = user.UserName;
            }

            return this.View();
        }
    }
}

UrbanSolution.Web/Views/Shared/_AdminUserTableRow.cshtml
@model AdminUserTableRowModel
@{
    var userAddToRoles = Model.User.UserNotInRoles?.Split(new[] {','}).Select(r => new SelectListItem(r, r));
    var userRemoveFromRoles = Model.User.UserRoles?.Split(new[] {','}).Select(r => new SelectListItem(r, r));
}

<td class="text-center">@Model.User.UserName</td>
<td class="text-center">@Model.User.Email</td>
<td class="text-center">
    @(@Model.User.LockoutEnd == null ? "Not Locked" : @Model.User.LockoutEnd.Value.ToString())
</td>
<td>
    @if (@Model.User.LockoutEnd != null)
    {
        <div class="form-inline text-center">
            <button onclick="unlockUser('@Model.User.Id')" type="button" class="btn btn-sm btn-success">Unlock</button>
        </div>
    }
    else
    {
        <div class="form-inline text-center">
            <select id="lockDays@(Model.User.Id)" name="LockDays" asp-items="Model.LockDays" class="form-control"></select>
            <button onclick="lockUser('@Model.User.Id')" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-lock"></i></button>
        </div>
    }

</td>
@*AddToRole*@
<td>
    @if (userAddToRoles != null && userAddToRoles.Any())
    {
        <div class="form-inline text-center">
            <select id="addToRole@(Model.User.Id)" asp-items="userAddToRoles" class="form-control"></select>
            <button onclick="addToRole('@Model.User.Id')" class="btn btn-sm btn-success" type="button">
                <i class="glyphicon glyphicon-ok"></i>
            </button>
        </div>
    }
</td>
@*RemoveFromRole*@
<td>
    @if (userRemoveFromRoles != null && userRemoveFromRoles.Any())
    {
        <div class="col-md-8">
            <select id="removeFromRole@(Model.User.Id)" asp-items="userRemoveFromRoles" class="form-control"></select>
        </div>
        <div class="col-md-2">
            <button onclick="removeFromRole('@Model.User.Id')" class="btn btn-sm btn-danger" type="button">
                <i class="glyphicon glyphicon-remove"></i>
            </button>
        </div>
    }
</td>

UrbanSolution.Web/Views/Shared/_AdminUsersListingPartial.cshtml
@model AdminUsersListingTableModel

@foreach (var user in Model.Users)
{
    IEnumerable<SelectListItem> userAddToRoles = user.UserNotInRoles?
        .Split(new[] { ',' }).Select(r => new SelectListItem(r, r));
    IEnumerable<SelectListItem> userRemoveFromRoles = user.UserRoles?
        .Split(new[] { ',' }).Select(r => new SelectListItem(r, r));

    <tr id="tr@(user.Id)">
        <td class="text-center">@user.UserName</td>
        <td class="text-center">@user.Email</td>
        <td class="text-center">
            @(user.LockoutEnd == null ? "Not Locked" : user.LockoutEnd.Value.ToString())
        </td>
        <td>
            @if (user.LockoutEnd != null)
            {
                //Unlock user unlockUser
                <div class="form-inline text-center">
                    <button onclick="unlockUser('@user.Id')" type="button" class="btn btn-sm btn-success">Unlock</button>
                </div>
            }
            else
            {
                //Lock  User
                <div class="form-inline text-center">
                    <select id="lockDays@(user.Id)" name="LockDays" asp-items="Model.LockDays" class="form-control"></select>
                    <button onclick="lockUser('@user.Id')" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-lock"></i></button>
                </div>
            }

        </td>
        @*AddToRole*@
        <td>
            @if (userAddToRoles != null && userAddToRoles.Any())
            {
                <div class="form-inline text-center">
                    <select id="addToRole@(user.Id)" asp-items="userAddToRoles" class="form-control"></select>
                    <button onclick="addToRole('@user.Id')" class="btn btn-sm btn-success" type="button">
                        <i class="glyphicon glyphicon-ok"></i>
                    </button>
                </div>
            }
        </td>
        @*RemoveFromRole*@
        <td>
            @if (userRemoveFromRoles != null && userRemoveFromRoles.Any())
            {
                <div class="col-md-8">
                    <select id="role@(user.Id)" name="Role" asp-items="userRemoveFromRoles" class="form-control"></select>
                </div>
                <div class="col-md-2">
                    <button onclick="removeFromRole('@user.Id')" class="btn btn-sm btn-danger" type="button">
                        <i class="glyphicon glyphicon-remove"></i>
                    </button>
                </div>
            }
        </td>
    </tr>
}

UrbanSolution.Web/Views/Shared/_IssueDetailsPartial.cshtml
@model IssueDetailsViewModel

    <div class="row">
        <div class="col-md-5">
            <div class="row">
                <h4>
                    <em class="text-info">
                        <i class="glyphicon glyphicon-cloud-upload"></i> @Model.Publisher
                    </em>
                    <em class="text-info">
                        <i class="glyphicon glyphicon-hourglass"></i> @Model.PublishedOn.ToShortDateString()
                    </em>
                </h4>
                <h4>
                    <em class="text-info">
                        <i class="glyphicon glyphicon-home"></i> @Model.AddressStreet
                    </em>
                </h4>
                <div>
                    <h4>
                        Type: <em class="text-info">@Model.Type.ToFriendlyName()</em>,
                        Region: <em class="text-info">@Model.Region</em>
                    </h4>
                </div>

                <em>@Model.Description</em>
            </div>
        </div>
        <div class="col-md-5 .issue-thumb" >
            <img src="@Model.PictureThumbnailUrl" alt="picture"/>
        </div>
    </div>

UrbanSolution.Web/Views/Shared/_IssueViewButtonsForDeleteAndEdit.cshtml
@model int

<a asp-area="Manager" asp-controller="UrbanIssue" asp-action="Edit" asp-route-id="@Model"
   class="btn btn-warning">
    Edit
</a>
<a asp-area="Manager" asp-controller="UrbanIssue" asp-action="Delete" asp-route-id="@Model"
   class="btn btn-danger">
    Delete
</a>

UrbanSolution.Web/Views/Shared/_IssuesListingPartial.cshtml
@model IssuesListingViewModel

@* When issues are listed in carousel (New Issues page)  *@
@*@if (Model.UseCarousel)
{
    @Html.DisplayFor(m => m.Issues)
}*@

@* When issues are listed normally (Approved Issues page) *@
<div class="row">
    <ul class="list-group">
        @Html.DisplayFor(m => m.Issues)
    </ul>
    <input type="hidden" id="pagesCount" value="@Model.PagesCount" />
    <input type="hidden" id="page" value="@Model.Page"/>
</div>

UrbanSolution.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Urban Solution</title>
    <environment include="Development">
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <i class="glyphicon glyphicon-globe"></i> Urban Solution
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @await Component.InvokeAsync("DynamicMenu")
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
    <partial name="_CookieConsentPartial" />
    <div class="container body-content">
        <partial name="_Messages" />
        @*js messages*@
        <div id="notifications">
            <div id="loadingBox" class="notification">
                <span>Loading …</span>
            </div>
            <div id="infoBox" class="notification">
                <span>Info</span>
            </div>
            <div id="errorBox" class="notification">
                <span>Error</span>
            </div>
        </div>
        @RenderBody()
        <footer class="footer">
            <hr />
            <div class="container">
                <span>&copy; 2020 - Urban Solution</span>
            </div>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

UrbanSolution.Web/Views/Shared/_ManagerActivity.cshtml
@model IEnumerable<ManagerActivitiesListingModel>

<table class="table table-bordered table-striped table table-hover">
    <thead>
    <tr>
        <th class="text-center"><strong>Username</strong></th>
        <th class="text-center"><strong>Action</strong></th>
        <th class="text-center"><strong>Date</strong></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var activity in Model)
    {
        <tr>
            <td class="text-center">@activity.UserName</td>
            <td class="text-center">@activity.Activity</td>
            <td class="text-center">@activity.DateTime</td>
        </tr>
    }
    </tbody>
</table>

UrbanSolution.Web/Views/Shared/_NewIssuesTablePartial.cshtml
@model NewIssuesTablePartialViewModel

<table class="table table-bordered table-striped table table-hover">
    <thead>
        <tr>
            <th class="text-center text-info"><strong>Picture</strong></th>
            <th class="text-center text-info"><strong>Title</strong></th>
            <th class="text-center text-info"><strong>Description</strong></th>
            <th class="text-center text-info"><strong>Address</strong></th>
            <th class="text-center text-info"><strong>PublishedOn</strong></th>
            <th class="text-center text-info"><strong>View</strong></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var issue in Model.Isssues)
        {
            <tr>
                <td class=".issues-thumb .img-responsive"><img src="@issue.PictureThumbnail" alt="pic"></td>
                <td class="text-center">@issue.Title</td>
                <td>@issue.Description</td>
                <td class="text-center">
                    @(issue.AddressStreet + Environment.NewLine + issue.Region)
                </td>
                <td class="text-center">@issue.PublishedOn</td>
                <td class="text-center">
                    <a asp-area=""
                       asp-controller="Issue"
                       asp-action="Details"
                       asp-route-id="@issue.Id">
                        View
                    </a>
                    <a asp-area="Manager"
                       asp-controller="UrbanIssue"
                       asp-action="Edit"
                       asp-route-id="@issue.Id">
                        Edit
                    </a>
                    <a asp-area="Manager"
                       asp-controller="UrbanIssue"
                       asp-action="Delete"
                       asp-route-id="@issue.Id">
                        Delete
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<input type="hidden" id="pagesCount" value="@Model.PagesCount" />
<input type="hidden" id="page" value="@Model.Page" />

UrbanSolution.Web/Views/Shared/_PagingPartial.cshtml
@model PagesModel
@{
    int maxButtonAfterCurrent = (Model.CurrentPage + 1 + ButtonsBeforeAndAfterCurrent);
    int minButtonBeforeCurrent = Math.Max((Model.CurrentPage - ButtonsBeforeAndAfterCurrent), 2);
}

<ul class="pagination">
    @* Enable or Disable Button for Previous Page *@
    @if (Model.CurrentPage == 1)
    {
        <li class="disabled">
            <a>
                <span aria-hidden="true">Previous</span>
            </a>
        </li>
    }
    else
    {
        <li>
            <a asp-action="Index"
               asp-route-page="@Model.PreviousPage"
               asp-route-sortby="@Model.SortBy"
               asp-route-sorttype="@Model.SortType"
               asp-route-searchtype="@Model.SearchType"
               asp-route-searchtext="@Model.SearchText"
               asp-route-filter="@Model.Filter">
                <span aria-hidden="true">Previous</span>
            </a>
        </li>
    }

    @* Show first page button *@
    @if (Model.CurrentPage == 1)
    {
        <li class="active"><a>1</a></li>
    }
    else
    {
        <li class="inactive">
            <a asp-action="Index"
               asp-route-page="1"
               asp-route-sortby="@Model.SortBy"
               asp-route-sorttype="@Model.SortType"
               asp-route-searchtype="@Model.SearchType"
               asp-route-searchtext="@Model.SearchText"
               asp-route-filter="@Model.Filter">
                1<span class="sr-only"></span>
            </a>
        </li>
    }

    @* Show buttons before  currentPage *@
    @if (Model.CurrentPage > 2)
    {
        @if (minButtonBeforeCurrent > 2)
        {
            //show button ...
            <li class="inactive">
                <a asp-action="Index"
                   asp-route-page="@((minButtonBeforeCurrent + 1) / 2)"
                   asp-route-sortby="@Model.SortBy"
                   asp-route-sorttype="@Model.SortType"
                   asp-route-searchtype="@Model.SearchType"
                   asp-route-searchtext="@Model.SearchText"
                   asp-route-filter="@Model.Filter">
                    <span aria-hidden="true">...</span>
                </a>
            </li>
        }
        @for (int i = minButtonBeforeCurrent; i <= (Model.CurrentPage - 1); i++)
        {
            <li class="inactive">
                <a asp-action="Index"
                   asp-route-page="@(i)"
                   asp-route-sortby="@Model.SortBy"
                   asp-route-sorttype="@Model.SortType"
                   asp-route-searchtype="@Model.SearchType"
                   asp-route-searchtext="@Model.SearchText"
                   asp-route-filter="@Model.Filter">
                    @(i)<span class="sr-only"></span>
                </a>
            </li>
        }
    }


    @* Show Current page button  - only if it is not the first or last page*@
    @if (Model.CurrentPage != 1 && Model.CurrentPage != Model.TotalPages)
    {
        <li class="active"><a>@Model.CurrentPage</a></li>
    }

    @* Show buttons after currentPage *@
    @for (int i = Model.CurrentPage + 1; i <= maxButtonAfterCurrent; i++)
    {
        if (i >= Model.TotalPages)
        {
            break;
        }

        if (i == maxButtonAfterCurrent)
        {
            <li class="inactive">
                <a asp-action="Index"
                   asp-route-page="@((Model.TotalPages + i) / 2)"
                   asp-route-sortby="@Model.SortBy"
                   asp-route-sorttype="@Model.SortType"
                   asp-route-searchtype="@Model.SearchType"
                   asp-route-searchtext="@Model.SearchText"
                   asp-route-filter="@Model.Filter">
                    <span aria-hidden="true">...</span>
                </a>
            </li>

            break;
        }

        <li class="inactive">
            <a asp-action="Index"
               asp-route-page="@(i)"
               asp-route-sortby="@Model.SortBy"
               asp-route-sorttype="@Model.SortType"
               asp-route-searchtype="@Model.SearchType"
               asp-route-searchtext="@Model.SearchText"
               asp-route-filter="@Model.Filter">
                @(i)<span class="sr-only"></span>
            </a>
        </li>
    }

    @* Show last page button *@
    @if (Model.TotalPages != 1)
    {
        @if (Model.CurrentPage == Model.TotalPages)
        {
            <li class="active"><a>@Model.TotalPages</a></li>
        }
        else
        {
            <li class="inactive">
                <a asp-action="Index"
                   asp-route-page="@(Model.TotalPages)"
                   asp-route-sortby="@Model.SortBy"
                   asp-route-sorttype="@Model.SortType"
                   asp-route-searchtype="@Model.SearchType"
                   asp-route-searchtext="@Model.SearchText"
                   asp-route-filter="@Model.Filter">
                    @(Model.TotalPages)<span class="sr-only"></span>
                </a>
            </li>
        }
    }


    @*Enable or Disable button for next page*@
    @if (Model.CurrentPage == Model.TotalPages)
    {
        <li class="disabled">
            <a aria-label="Next">
                <span aria-hidden="true">Next</span>
            </a>
        </li>
    }
    else
    {
        <li>
            <a asp-action="Index"
               asp-route-page="@(Model.NextPage)"
               asp-route-sortby="@Model.SortBy"
               asp-route-sorttype="@Model.SortType"
               asp-route-searchtype="@Model.SearchType"
               asp-route-searchtext="@Model.SearchText"
               asp-route-filter="@Model.Filter"
               aria-label="Next">
                <span aria-hidden="true">Next</span>
            </a>
        </li>
    }

</ul>

UrbanSolution.Web/Views/Shared/_ShowGoogleMapForGetingAddress.cshtml
<script>
    var map;
    var place;
    var address;
    var coordinates = {};

    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'),
            {
                center: { lat: 42.138893, lng: 24.741101 },
                zoom: 13
            });

        var input = document.getElementById('pac-input');

        var autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.bindTo('bounds', map);

        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        var infowindow = new google.maps.InfoWindow();
        var infowindowContent = document.getElementById('infowindow-content');
        infowindow.setContent(infowindowContent);
        var marker = new google.maps.Marker({
            map: map
        });
        marker.addListener('click',
            function() {
                infowindow.open(map, marker);
            });

        autocomplete.addListener('place_changed',
            function() {
                infowindow.close();
                place = autocomplete.getPlace();
                if (!place.geometry) {
                    return;
                }

                if (place.geometry.viewport) {
                    map.fitBounds(place.geometry.viewport);
                } else {
                    map.setCenter(place.geometry.location);
                    map.setZoom(17);
                }

                coordinates.latitude = place.geometry.location.lat();
                coordinates.longitude = place.geometry.location.lng();

                marker.setPlace({
                    placeId: place.place_id,
                    location: place.geometry.location
                });

                marker.setVisible(true);

                address = place.name.trim();

                infowindowContent.children['place-name'].textContent = place.name;
                infowindowContent.children['place-id'].textContent = place.place_id;
                infowindowContent.children['place-address'].textContent = place.formatted_address;

                infowindow.open(map, marker);
            });
    }

    $("#GetAddress").click(function() {
        $("#Address").val(address);
        $("#Latitude").val(coordinates.latitude);
        $("#Longitude").val(coordinates.longitude);
    });
</script>

UrbanSolution.Web/Views/Shared/_SlickCarouselIssuesListingScriptPartial.cshtml
<script>
    $(document).ready(function () {
        $('.slick-issues').slick({
            infinite: true,
            slidesToShow: 4,
            slidesToScroll: 1,
            dots: false,
            arrows: false,
            autoplay: false,
            autoplaySpeed: 50
        });
    });
</script>

UrbanSolution.Web/Views/Shared/_SlickCarouselScriptPartial.cshtml
<script>
    $(document).ready(function () {
        $('.slick-fade').slick({
            dots: false,
            arrows: false,
            infinite: false,
            autoplay: true,
            speed: 500,
            fade: true,
            cssEase: 'linear',
            centerMode: true
        });

        $('.left').click(function () {
            $('.slick-fade').slick('slickPrev');
        });

        $('.right').click(function () {
            $('.slick-fade').slick('slickNext');
        });
    });
</script>

UrbanSolution.Web/Views/Shared/_TinyMceScripts.cshtml
<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>

<script>
    tinymce.init({
        selector: '#Content'
    });
</script>

UrbanSolution.Web/Views/Shared/_UrbanIssueButtonsForAllManagerActions.cshtml
@model IssueDetailsModel

@if (!Model.IsApproved)
{
    <a asp-area="Manager" asp-controller="UrbanIssue" asp-action="Approve" asp-route-id="@Model.Id"
       class="btn btn-primary">
        Approve
    </a>
}
@if (!Model.HasResolved)
{
    @await Html.PartialAsync("_IssueViewButtonsForDeleteAndEdit", Model.Id)
}
@if (Model.IsApproved && !Model.HasResolved)
{
    <a asp-area="Manager" asp-controller="Resolved" asp-action="Upload" asp-route-id="@Model.Id"
       class="btn btn-primary">
        Upload Resolved
    </a>
}